### ISSUE TITLE
crashing as soon as I start the container 

### ISSUE THREAD

**Issue by treypop** [baudneo/cync-lan#2]
whenever I start the container it crashes. 
This is what the log gives me.
`2024-04-06 14:09:49 Traceback (most recent call last):
2024-04-06 14:09:49   File "/root/cync-lan/cync-lan.py", line 3159, in <module>
2024-04-06 14:09:49     raise FileNotFoundError(f"Config file not found: {config_file}")
2024-04-06 14:09:49 FileNotFoundError: Config file not found: /root/cync-lan/config/cync_mesh.yaml`

**Comment by baudneo** [comment]
Did you export a config file from the cloud and bind mount it into the container?

In the README, it has info on how to download the script and export the devices to a YAML config file. You then bind mount that config file into the container, see the example docker-compose YAML file `volumes:` section.

**Comment by baudneo** [comment]
I have updated the README with better install docs. See [INSTALL.md](https://github.com/baudneo/cync-lan/blob/python/docs/INSTALL.md)

**Comment by treypop** [comment]
Thank you this cleared up my confusion. I ended up just doing the virtualenv method. But now having problems with mqtt but that's a different issue.
