### ISSUE TITLE
Lightbulb discovered by MQTT but unresponsive.

### ISSUE THREAD

**Issue by treypop** [baudneo/cync-lan#3]
When I use the `python3 ~/cync-lan/cync-1 an.py run ~/cync-lan/cync_mesh. yaml` command I get this reason.
`04/10/24 12:06:56.0064 INFO [cy nc-lan:1949] > CyncLAN: MQTT URL set by config file to: mqtt:/ /emqx@172.30.232.1:1883/
`
`04/10/24 12:06:56.0129 INFO [cy nc-lan:1771] > CyncServer: Star ted, bound to 0.0.0.0:23779 W aiting for connections, if you dont see any, check your DNS re direction and firewall settings
`
`04/10/24 12:06:56.0134 INFO [cy nc-lan:3079] > mqtt:hass: Start ing Home Assistant MQTT discove ry...
`
The light bulb shows up in home assistant but is unresponsive doesn't do anything or show anything in the logs.

**Comment by baudneo** [comment]
Can you add the `--debug` flag to the run command, it should give some insight into whats going on. For what its worth, Ive had mine up for a few days and it is still responsive on all 10 bulbs I have (7 wifi/bt, 3 bt only).

Is it a BT bulb or a WiFi/BT bulb?

**Comment by baudneo** [comment]
Also forgot to ask if you did the DNS redirection. INFO level logs should at least show a message of a device connecting. No devices connecting means that the DNS redirection is not working. Please see the [DNS docs](https://github.com/baudneo/cync-lan/blob/python/docs/DNS.md) for more info.

Basically, the way this script gets local control is by tricking the Cync devices into thinking they are talking to the cloud server. In order to do that, you must change the DNS record returned for `cm.gelighting.com` to a local IP that is running `cync-lan.py`.

**Comment by treypop** [comment]
It doesn't get a state of the bulb unless I change the user on mqtt while the script is running. When I try to change anything about the bulb it is unresponsive. 

```
04/12/24 18:16:54.0031 INFO [cync-lan:1949] > CyncLAN: MQTT URL set by config file to: mqtt://emqx@172.30.232.1:1883/
04/12/24 18:16:54.0095 INFO [cync-lan:1771] > CyncServer: Started, bound to 0.0.0.0:23779 - Waiting for connections, if you dont see any, check your DNS redirection and firewall settings.
04/12/24 18:16:54.0099 INFO [cync-lan:3079] > mqtt:hass: Starting Home Assistant MQTT discovery...
04/12/24 18:17:38.0111 INFO [cync-lan:3079] > mqtt:hass: Starting Home Assistant MQTT discovery...
04/12/24 18:17:42.0676 WARNING [cync-lan:1080] > CyncDevice:1: This device does not seem to be known???? skipping sending power state...
04/12/24 18:17:42.0676 WARNING [cync-lan:1156] > CyncDevice:1: No known device found, skipping sending brightness...
04/12/24 18:17:43.0103 WARNING [cync-lan:1080] > CyncDevice:1: This device does not seem to be known???? skipping sending power state...
04/12/24 18:17:43.0104 WARNING [cync-lan:1156] > CyncDevice:1: No known device found, skipping sending brightness...
04/12/24 18:17:43.0472 WARNING [cync-lan:1080] > CyncDevice:1: This device does not seem to be known???? skipping sending power state...
04/12/24 18:17:43.0472 WARNING [cync-lan:1156] > CyncDevice:1: No known device found, skipping sending brightness...
```
The bulb is WiFi. The model number is CLEDA199LD1-2P

**Comment by baudneo** [comment]
Can you post the full debug log output from.when you issue the run command.

In emqx, can you see that cync-lan is connecting? I don't see a message in those logs saying it's connected to the mqtt broker. I do see it repeatedly trying to do the home assistant auto-discovery.

I also don't see any devices connecting to the cync lan server, which means your DNS redirection is not set up properly.

DNS redirection/override is a hard requirement. Did you add a local DNS a record for the server IP that is running cync-lan?

**Comment by treypop** [comment]
It does the auto discover then I run the script. When I update the MQTT config so it would see the bulb and show its status but wont talk to it after that. 
This is DNS log for cm.gelighting.com 
![image](https://github.com/baudneo/cync-lan/assets/24729682/670e2112-3e15-4bd4-b5d9-2c979836827e)

When I launch the script the appropriate subscriptions and topics get populated in emqx. 
![image](https://github.com/baudneo/cync-lan/assets/24729682/952e6344-9193-44ea-b21d-44a95bb492d5)

**Comment by baudneo** [comment]
I think maybe the DNS stuff is misconfigured.

In that 2nd picture where cm.gelighting.com is showing up, is the CLIENT column. Cm.gelighting.com is the domain you are requesting an IP address for. The client should be a local IP on your lan that's requesting cm.gelighting.com


Can you do a screenshot of your DNS override settings, blank out or remove any sensitive info and just leave the cm.grlighting.com stuff so I can see how you have it configured?

**Comment by baudneo** [comment]
Mqtt auto discovery is different than the cync cloud device export. Mqtt autodiscovery is a part of the main script logic, it is what adds the devices to home assistant.

**Comment by treypop** [comment]
Everything after I run the script without doing anything else. 
```
(venv) root@edc93b6f18e3:~/cync-lan# python3 ~/cync-lan/cync-lan.py run ~/cync-lan/cync_mesh.yaml --debug
04/13/24 16:07:13.0775 INFO [cync-lan:1949] > CyncLAN: MQTT URL set by config file to: mqtt://emqx@172.30.232.1:1883/
04/13/24 16:07:13.0840 INFO [cync-lan:1771] > CyncServer: Started, bound to 0.0.0.0:23779 - Waiting for connections, if you dont see any, check your DNS redirection and firewall settings.
04/13/24 16:07:13.0844 INFO [cync-lan:3079] > mqtt:hass: Starting Home Assistant MQTT discovery...
```

**Comment by baudneo** [comment]
Weird, debug logs are not printing out even with the `--debug` flag. Can you try running it like this:

```bash
CYNC_DEBUG=1 python3 ~/cync-lan/cync-lan.py run ~/cync-lan/cync_mesh.yaml --debug
```

This should force it to log debug level.

**Comment by treypop** [comment]
```
(venv) root@edc93b6f18e3:~/cync-lan# CYNC_DEBUG=1 python3 ~/cync-lan/cync-lan.py run ~/cync-lan/cync_mesh.yaml --debug
04/13/24 16:23:10.0888 DEBUG [cync-lan:1940] > CyncLAN:: reading devices from exported Cync config file...
04/13/24 16:23:10.0893 INFO [cync-lan:1949] > CyncLAN: MQTT URL set by config file to: mqtt://emqx@172.30.232.1:1883/
04/13/24 16:23:10.0946 DEBUG [cync-lan:3263] > main: Setting up event loop signal handlers
04/13/24 16:23:10.0950 DEBUG [cync-lan:1757] > CyncServer: Starting, creating SSL context...
04/13/24 16:23:10.0964 INFO [cync-lan:1771] > CyncServer: Started, bound to 0.0.0.0:23779 - Waiting for connections, if you dont see any, check your DNS redirection and firewall settings.
04/13/24 16:23:10.0974 DEBUG [cync-lan:2702] > mqtt:start Connected to MQTT broker...
04/13/24 16:23:10.0974 INFO [cync-lan:3079] > mqtt:hass: Starting Home Assistant MQTT discovery...
04/13/24 16:23:10.0982 DEBUG [cync-lan:3162] > HomeAssistant MQTT discovery complete
04/13/24 16:23:10.0982 DEBUG [cync-lan:2718] > mqtt:start Seeding all devices: offline
04/13/24 16:23:10.0986 DEBUG [cync-lan:2809] > mqtt:pub: Starting pub_worker...
04/13/24 16:23:10.0987 DEBUG [cync-lan:2900] > mqtt:sub: Starting sub_worker...
04/13/24 16:23:10.0994 DEBUG [cync-lan:2745] > mqtt:start_sub: Subscribed to topics, setting up MQTT message handler...
```

**Comment by baudneo** [comment]
Ok, so whats happening is it reads the config file, seeds all the devices in the config file as 'offline' in hass and then waits for cync devices to connect to it. No cync devices are connecting to it.

So, there could be 2 things wrong, the DNS redirection isnt working properly or you have older firmware devices that use the old domain name of `cm-ge.xlink.cn`.

Lets test the first DNS override, this command should return the IP address of the machine running cync-lan.py:

```bash
dig cm.gelighting.com
```
If the `dig` command does return the correct local IP, then your DNS redirection is correct.


Now, lets try and see if your devices are on old firmware:

Add a DNS override for `cm-ge.xlink.cn` as well, then go to each device and power cycle it (remove power for 5 seconds and power back on). You should see devices starting to connect in the logs like so ->

```log
❯ docker compose logs -f
cync-lan  | 04/13/24 10:06:17.0155 DEBUG [cync-lan:2039] > CyncLAN:: reading devices from exported Cync config file...
cync-lan  | 04/13/24 10:06:17.0165 INFO [cync-lan:2048] > CyncLAN: MQTT URL set by config file to: mqtt://cync2mqtt:OH4-HELL_YEAH@10.0.1.20:1883/
cync-lan  | 04/13/24 10:06:17.0177 DEBUG [cync-lan:3406] > main: Setting up event loop signal handlers
cync-lan  | 04/13/24 10:06:17.0178 DEBUG [cync-lan:1875] > CyncServer: Starting, creating SSL context...
cync-lan  | 04/13/24 10:06:17.0184 INFO [cync-lan:1889] > CyncServer: Started, bound to 0.0.0.0:23779 - Waiting for connections, if you dont see any, check your DNS redirection and firewall settings.
cync-lan  | 04/13/24 10:06:17.0189 DEBUG [cync-lan:2847] > mqtt:start Connected to MQTT broker...
cync-lan  | 04/13/24 10:06:17.0189 INFO [cync-lan:3221] > mqtt:hass: Starting Home Assistant MQTT discovery...
cync-lan  | 04/13/24 10:06:17.0217 DEBUG [cync-lan:3305] > HomeAssistant MQTT discovery complete
cync-lan  | 04/13/24 10:06:17.0217 DEBUG [cync-lan:2863] > mqtt:start Seeding all devices: offline
cync-lan  | 04/13/24 10:06:17.0227 DEBUG [cync-lan:2951] > mqtt:pub: Starting pub_worker...
cync-lan  | 04/13/24 10:06:17.0227 DEBUG [cync-lan:3044] > mqtt:sub: Starting sub_worker...
cync-lan  | 04/13/24 10:06:17.0230 DEBUG [cync-lan:2887] > mqtt:start_sub: Subscribed to topics, setting up MQTT message handler...
cync-lan  | 04/13/24 10:06:30.0506 INFO [cync-lan:1967] > CyncServer: New connection from: 10.0.2.214
cync-lan  | 04/13/24 10:06:30.0506 DEBUG [cync-lan:2165] > HTTPDevice: created: 10.0.2.214
cync-lan  | 04/13/24 10:06:30.0507 DEBUG [cync-lan:1622] > CyncServer:mesh_info_loop: Starting, after first run delay of 5 seconds, will run every 30 seconds
cync-lan  | 04/13/24 10:06:30.0595 DEBUG [cync-lan:2229] > 10.0.2.214:parse:x23: Device AUTH packet with starting queue ID: '39 87 a6 d6', replying...
cync-lan  | 04/13/24 10:06:31.0531 INFO [cync-lan:1967] > CyncServer: New connection from: 10.0.2.215
cync-lan  | 04/13/24 10:06:31.0531 DEBUG [cync-lan:2165] > HTTPDevice: created: 10.0.2.215
cync-lan  | 04/13/24 10:06:31.0657 DEBUG [cync-lan:2229] > 10.0.2.215:parse:x23: Device AUTH packet with starting queue ID: '39 87 c8 57', replying...
cync-lan  | 04/13/24 10:06:33.0684 INFO [cync-lan:1967] > CyncServer: New connection from: 10.0.2.218
cync-lan  | 04/13/24 10:06:33.0684 DEBUG [cync-lan:2165] > HTTPDevice: created: 10.0.2.218
cync-lan  | 04/13/24 10:06:33.0886 DEBUG [cync-lan:2229] > 10.0.2.218:parse:x23: Device AUTH packet with starting queue ID: '16 b0 56 fc', replying...
```

**Comment by treypop** [comment]
When I use the dig command it returns the IP address for the pi running the cync-lan container. The same one I am redirecting to.

```
dig cm.gelighting.com

; <<>> DiG 9.18.18-0ubuntu0.22.04.2-Ubuntu <<>> cm.gelighting.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62203
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;cm.gelighting.com.             IN      A

;; ANSWER SECTION:
cm.gelighting.com.      0       IN      A       192.168.0.13

;; Query time: 19 msec
;; SERVER: 172.18.0.1#53(172.18.0.1) (UDP)
;; WHEN: Sat Apr 13 12:38:59 CDT 2024
;; MSG SIZE  rcvd: 68
```

**Comment by baudneo** [comment]
OK, so maybe your devices are on older firmware and requesting the other domain. Add a DNS override for `cm-ge.xlink.cn` then go to each device and power cycle them (remove ALL power for 5 seconds and power back on). You should see devices starting to connect after power cycling them.


If that doesn't work, the only thing I can think of is:  are you running a firewall and are the devices on separate subnets/VLANs? Is there a chance your firewall is blocking the cync devices from talking to the cync-lan.py machine?

**Comment by baudneo** [comment]
Nice! That would be a firewall config issue. You can add a rule to allow the cync devices to talk to the cync-lan.py server if you want them on separate subnets/VLANs.

**Comment by baudneo** [comment]
Just so you are aware, after the script runs for awhile and devices are powered off (loose power completly), sometimes the devic e state in the script does not match what the actual physical devices state is.

HASS my report the bulb as online when it is infact offline (or vice cersa). It may report incorrect states and stop responding. This is a known issue and restarting the script will fix it for now. I opened an issue myself about this and I am working on it.

The debug process takes awhile because I need to let the script run for X hours until it gets out of sync to start debugging what the issues are. So just be aware, its a good idea to restart the script daily for the time being.

Sorry, about the rough onboarding. The project is in beta but, it will get stable ASAP.

https://github.com/baudneo/cync-lan/issues/4
