### ISSUE TITLE
Getting error when running script to export cloud device config to ./cync_mesh.yaml

### ISSUE THREAD

**Issue by ahmedn4021** [baudneo/cync-lan#6]
I followed all the steps and when I run the script to export could device config, I get the following error. 

 python3 ~/cync-lan/cync-lan.py export ~/cync-lan/cync_mesh.yaml --save-auth --auth-output ~/cync-lan/.auth.yaml
  File "/root/cync-lan/cync-lan.py", line 1477
    if (_r_task := device.tasks.receive) is not None:
                ^
SyntaxError: invalid syntax

**Comment by baudneo** [comment]
What version of python are you running? I think the walrus operator was added in 3.8.

**Comment by baudneo** [comment]
Hello, if you have resolved your issue, can you please close this?

If you haven't resolved your issue, I would need some more information to help you.
